version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/.env:/app/.env

      #- frontend-node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - MODE_ENV=development
    #stdin_open: true
    #tty: true
    #depends_on:
    #  - backend
    restart:
      unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - backend-node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - MODE_ENV=development
    stdin_open: true
    tty: true
    #depends_on:
    #  - database
    restart:
      unless-stopped

volumes:
  #frontend-node_modules:
  backend-node_modules: